app = "bjj-schedule-app"
primary_region = "nrt"

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"
  NODE_ENV = "production"
  NEXT_PUBLIC_SUPABASE_URL = "https://your-supabase-url.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "your-supabase-anon-key"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024