# fly.toml app configuration file generated for bjj-schedule-app on 2025-04-11T22:44:36Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bjj-schedule-app'
primary_region = 'nrt'

[build]
  dockerfile = "Dockerfile"

[env]
  NEXT_PUBLIC_SUPABASE_ANON_KEY = 'your-supabase-anon-key'
  NEXT_PUBLIC_SUPABASE_URL = 'https://your-supabase-url.supabase.co'
  NODE_ENV = 'production'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
